apiVersion: v1
kind: Deployment
metadata:
  name: calculator-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      - name: calculator
        image: deepakn200/calculator:latest
        ports:
          - containerPort: 5000