pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git "https://github.com/deepakn-0603/calculator-app.git"
            }   
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t calculator-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -p 5000:5000 calculator-app'
            }
        }
    }
}